version: "3.9"

services:
  lab01-database:
    image: postgres
    container_name: lab01-database
    environment:
      - POSTGRES_DB=my_db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    ports:
      - 5432:5432

  rabbitmq:
    image: "rabbitmq:3.8-management-alpine"
    container_name: nodejs-rabbitmq-rabbitmq
    hostname: rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - "./.rabbitmq_data:/var/lib/rabbitmq/mnesia"
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
